name: Remote update execution
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
            cd /home/malangdataguy/airflow_mdg/dags
            git config --global --add safe.directory /home/malangdataguy/airflow_mdg/dags
            git checkout master
            git pull origin master --allow-unrelated-histories
